name:                pp-besm
version:             0.1.0.0
github:              "githubuser/pp-besm"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/pp-besm#readme>

dependencies:
- base >= 4.7 && < 5
- text

library:
  source-dirs: src
  dependencies:
  - bv-sized
  - cereal
  - megaparsec
  - text
  - prettyprinter
  - digits
  - charset
  ghc-options:
  - -fwarn-incomplete-uni-patterns
  - -fwarn-incomplete-patterns
  - -fdiagnostics-color=always
executables:
  pp-besm:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pp-besm
    - prettyclass
    - bv-sized
    - optparse-simple

tests:
  pp-besm-test:
    main:                Spec
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pp-besm
    - hedgehog
    - prettyprinter
